name: Check Flake

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [ 'statix check', 'deadnix -f', 'nix fmt', 'typos', 'nix flake check --no-build --all-systems' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run Checks
        run: |
          case "${{ matrix.command }}" in
            "nix fmt")
              echo "Running nix fmt"
              ${{ matrix.command }}
              ;;
            "nix flake check --no-build --all-systems")
              echo "Running nix flake check"
              ${{ matrix.command }}
              ;;
            *)
              echo "Running ${{ matrix.command }}"
              nix develop --command ${{ matrix.command }}
              ;;
          esac