---

name: Check NixOS flake

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run checks
        run: nix flake check --all-systems --no-update-lock-file
...