name: Check Flake

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: check-flake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1

      - name: Run Checks
        run: nix flake check