name: Check Flake

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['statix check', 'deadnix -f', 'nix fmt', 'typos']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run Checks
        run: |
          if [ "${{ matrix.command}}" == "nix fmt" ]; then
            nix fmt
          else
            nix develop --command ${{ matrix.command }}
          fi