---
name: Run Checks

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 10

    concurrency:
      group: ${{ github.ref }}-check
      cancel-in-progress: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Flake (statix & nixfmt-classic)
        run: nix flake check