name: Update Flake

on: workflow_dispatch

jobs:
  update-flake:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Update flake.lock
        run: nix flake update

      - name: Run checks
        run: nix flake check --all-systems

      - name: Check if system evals
        run: nix eval .#nixosConfigurations.Skadi.config.system.build.toplevel